These programs are used to convert a given zeolite structure (for now, only works for zeolites containing only Si and O. No cations, aluminum or other species).

Included are several examples of bash files that can somewhat automate this process.

1. Starting with zeolite file, run
python JonTest1.py <file.xyz>
This will output a xyz file corresponding to the unit cell of the ZIF version. The ZIF is generated by 
-Replacing Si atoms with Zn
-Stretching coordinates of all atoms uniformly so as to make the Zn-Zn distance approximately that of a ZIF (the exact cutoff is hardcoded in the program, it can be altered).
-Replacing the Oxygen atoms with Imidizolate linkers

Since these are "hypothetical" structures and generated based on geometric considerations, it is important to energy minimize them before doing any sort of analysis.
